# Generated by Django 2.1.5 on 2019-04-11 19:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HDMRequestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('year', models.DateField()),
                ('authors_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), size=10)),
                ('abstract', models.TextField(max_length=1024)),
                ('venue', models.CharField(blank=True, max_length=128, null=True)),
                ('paper_id', models.UUIDField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
